#!/usr/bin/env ruby
require 'fileutils'

puts 'Molecular docking input writer'

dir = File.dirname __FILE__

FileUtils.cp_r(File.join(dir, 'simulation_binaries'), '.')

%x[chmod a+x simulation_binaries/*]
%x[chmod a+x simulation_binaries/src/*]
